language: groovy
jdk: openjdk8

matrix:
  include:
  - env: TEST_SHARD=shard_1 JENKINS_VERSION='jenkins_2.190.3' TOXENV=py35
    addons:
      apt:
        packages: python3-pip
  - env: TEST_SHARD=shard_2 JENKINS_VERSION='jenkins_2.190.3' TOXENV=py35
    addons:
      apt:
        packages: python3-pip

dist: xenial
sudo: required

branches:
  only:
    - master

services:
    - docker

# Cache the gradle wrapper to avoid downloading each time
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

#cache:
    #directories:
        #- $HOME/.gradle/caches/
        #- $HOME/.gradle/wrapper/

before_install:
    # browser set up for e2e tests
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    # install requirements and build the container
    - make plugins
    - sudo make requirements
    - cp local_env.sh.sample local_env.sh && source local_env.sh
    - make build
    - make run
    - export BOKCHOY_HEADLESS=true

addons:
    firefox: '69.0'

script:
    - export CI_SYSTEM='travis'
    - make healthcheck
    - make e2e
