language: groovy
jdk: openjdk8

env:
  global:
    - JENKINS_VERSION='jenkins_2.263.4'
  jobs:
    - TEST_SHARD=shard_1 TOXENV=py38
    - TEST_SHARD=shard_2 TOXENV=py38
      
addons:
  apt:
    packages: python3-pip

dist: xenial
sudo: required

branches:
  only:
    - master

services:
    - docker

# Cache the gradle wrapper to avoid downloading each time
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_install:
    # browser set up for e2e tests
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    # Install python3.8 interpreter
    - sudo add-apt-repository ppa:deadsnakes/ppa -y;
    - sudo apt-get update -y;
    - sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;
    - virtualenv -p python3.8 venv;
    - source venv/bin/activate;
    # install requirements and build the container
    - make plugins
    - make requirements
    - cp local_env.sh.sample local_env.sh && source local_env.sh
    - make build
    - make run
    - export BOKCHOY_HEADLESS=true


addons:
    firefox: '69.0'

# Skip the "install" step, as it will cause travis to automatically call 'gradle assemble'.
# We don't want to do this, as it will try to compile the groovy code in `src`, which will
# cause errors because we are not pinning dependencies in the gradle file. Compilation/assembly
# is unnecessary, as the code will be run by Jenkins and we are not building artifacts here.
# see: https://github.com/travis-ci/travis-ci/issues/8667#issuecomment-366589908
install: skip

script:
    - export CI_SYSTEM='travis'
    - make quality
    - make healthcheck
    - make e2e
