language: groovy
env:
    - JENKINS_VERSION='jenkins_2.89.4'

dist: trusty
sudo: required

branches:
  only:
    - master

services:
    - docker

# Cache the gradle wrapper to avoid downloading each time
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_install:
    # browser set up for e2e tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget https://s3.amazonaws.com/vagrant.testeng.edx.org/geckodriver-v0.15.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    # install requirements and build the container
    - make plugins
    - sudo make requirements
    - cp local_env.sh.sample local_env.sh && source local_env.sh
    - make build
    - make run

addons:
    firefox: '52.0.1'

script:
    - export CI_SYSTEM='travis'
    - make quality
    - make healthcheck
    - make e2e
