---
ADV_PROPERTIES: 'C'
DEFAULT_CONTENT_TYPE: 'text/html'
DEFAULT_SUBJECT: 'HEY'
DEFAULT_BODY_PATH: 'email_ext/default_body.txt'
EMERGENCY_REROUTE: ''
DEFAULT_REPLYTO: 'ME'
DEFAULT_PRESEND_SCRIPT_PATH: 'email_ext/pre_build_script.groovy'
DEFAULT_POSTSEND_SCRIPT_PATH: 'email_ext/post_build_script.groovy'
DEBUG_MODE: 'TRUE' 
MAX_ATTACHMENT_SIZE: '9999'
DEFAULT_RECIPIENTS: 'NOBODY'
ADD_PRECEDENCE_BULK: 'TRUE'
ALLOWED_DOMAINS: 'NONE'
EXCLUDED_COMMITTERS: 'HIM'
REQUIRE_ADMIN_FOR_TEMPLATE_TESTING: 'TRUE'
WATCHING_ENABLED: 'TRUE'
ALLOW_UNREGISTERED_ENABLED: 'TRUE'
USE_LIST_ID: 'true'
LIST_ID': '12345'
TRIGGERS:
    - 'FailureTrigger'
    - 'FirstFailureTrigger'
    - 'FirstUnstableTrigger'
    - 'FixedTrigger'
    - 'FixedUnhealthyTrigger'
    - 'ImprovementTrigger'
    - 'NotBuiltTrigger'
    - 'NthFailureTrigger'
    - 'PreBuildScriptTrigger'
    - 'PreBuildTrigger'
