---
SERVER_API_URL: 'https://api.github.com'
ACCESS_TOKEN: 'accessTokenString'
ADMIN_LIST:
    - 'admin1'
    - 'admin2'
REQUEST_TESTING_PHRASE: 'retest this PR please'
WHITE_LIST_PHRASE: 'add this github user'
BLACK_LIST_LABELS:
    - 'foo'
    - 'bar'
OK_PHRASE: 'this is OK to test'
RETEST_PHRASE: 'please retest'
BLACKLIST_AUTHORS: 'badPerson1 nefarious123'
SKIP_PHRASE: 'skip tests'
CRON_SCHEDULE: 'H/5 * * * *'
USE_COMMENTS: true
USE_DETAILED_COMMENTS: false
MANAGE_WEBHOOKS: false
UNSTABLE_AS: 'pending'
AUTO_CLOSE_FAILED_PRS: false
DISPLAY_ERRORS_DOWNSTREAM: true
GITHUB_AUTH: 'test'
CANCEL_BUILD_ON_UPDATE: true
SIMPLE_STATUS: 'simple status'
PUBLISH_JENKINS_URL: 'myjenkinsinstance.com'
BUILD_LOG_LINES_TO_DISPLAY: 25
RESULT_MESSAGES:
    - STATUS: 'pending'
      MESSAGE: 'this is pending'
    - STATUS: 'failure'
      MESSAGE: 'this was a failure'
CREDENTIALS_ID: 'secretFile1'
SHARED_SECRET: ''
